import type { GoalReviewRecord, RunState, TicketState } from "../core/state.ts";
import { isFinished } from "../core/state.ts";
import { loadTickets, type Ticket } from "../core/ticket.ts";
import { contextBudget, firesAtRunEnd, goalCheckpointIsAdvisory, goalFiresCheckpointsMidRun, DEFAULT_MAX_REPLANS } from "../config/config.ts";
import { reviewSummary, runReviewAgent } from "./reviewer.ts";
import { runCommandFromVerify } from "./visual.ts";
import { detectGameCanvas, RAILHEAD_AGENT_NAMES } from "../core/project-assets.ts";
import { touchesVisualSurface } from "../context/surface.ts";
import { pushLearnings, readLearnings } from "../context/learnings.ts";
import { pushDigest, readDigest } from "../context/digest.ts";
import { applyCharterRevisions, parseCharterRevisions } from "../context/coherence.ts";
import { buildGoalReviewPrompt, parseCorrectiveTickets, parseGoalVerdict, findingsEchoLastRound, remainingPlanGroups, splitAnchoredBlockers } from "./goal-review.ts";
import { processCorrectiveFindings, type RunTicket } from "./corrective.ts";
import { replanFromCheckpoint, drainFrontier } from "./replan.ts";
import { loadContracts, summarizeContracts } from "../core/contracts.ts";
import * as git from "../core/git.ts";
import { eventPath, writeState } from "../core/ledger.ts";
import { hasInteractionEvidence, parseToolCalls } from "./evidence.ts";
import { requiresRealInputEvidence, type ProjectInterface } from "../config/interface.ts";
import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { nowClock } from "../cli/overview.ts";
import { readVisionCapabilityFor } from "../execute/vision-probe.ts";
import { addPendingCheckpoint, clearPendingCheckpoint } from "../core/pending-checkpoints.ts";

/**
 * Issue #19: Check whether a goal-review checkpoint has been reached after
 * this ticket committed, and if so, run the goal review. A checkpoint is
 * reached when:
 *
 * - The planner emitted group labels: all tickets in the just-completed group
 *   are committed, and this group has not been goal-reviewed before.
 * - No group labels: every `fallback_cadence` committed tickets triggers a
 *   synthetic checkpoint (named `checkpoint-N`).
 *
 * Returns "fail" only when a corrective ticket generated by the goal review
 * itself fails; "pass" covers pass, inconclusive, and no-checkpoint-reached.
 */
export async function goalReviewAtCheckpoint(
  state: RunState,
  ledger: string,
  ticket: TicketState,
  _parsed: Ticket,
  runTicket: RunTicket,
): Promise<"pass" | "fail"> {
  const cfg = state.config.goal_review;
  // Issue #73: group-checkpoint triggers fire under `full`/`medium`; `light`
  // defers goal review to run end, `off` disables it. ADR 0029 (#102): a
  // `checkpoint_action: "advisory"` goal gate fires the judge at group
  // boundaries even under `light` — advisory-only, corrective at run end.
  if (!cfg || !goalFiresCheckpointsMidRun(cfg)) return "pass";
  const goalModel = state._models?.goal ?? null;
  if (!goalModel) return "pass";

  const checkpoints = goalCheckpointsToFire(state, ticket);
  if (checkpoints.length === 0) return "pass";

  for (const group of checkpoints) {
    // gh: persist the owed marker BEFORE spawning the review agent. The ticket
    // is already committed; a stop in this window would otherwise skip the
    // checkpoint forever (resume only inspects the ticket that just committed).
    addPendingCheckpoint(state, "goal", group);
    await writeState(ledger, state);
    const outcome = await runGoalReview(state, ledger, group, runTicket);
    clearPendingCheckpoint(state, "goal", group);
    await writeState(ledger, state);
    if (outcome === "fail") return "fail";
  }
  return "pass";
}

/**
 * Determine which group checkpoint(s) are now reached after `ticket`
 * committed. Returns group labels to review (empty if no checkpoint).
 *
 * Group-based: after the last ticket in a group commits, the checkpoint fires.
 * We detect this by checking whether the ticket that just committed belongs to
 * a group, and whether all tickets in that group are now committed.
 *
 * Fallback cadence: when the ticket that just committed has no group label,
 * fire a synthetic `checkpoint-N` every `fallback_cadence` committed tickets.
 *
 * ADR 0044 cadence ceiling (goal gate only): the goal checker passes
 * `cadenceCeiling`, which also fires a synthetic checkpoint when the commits
 * since the LAST goal checkpoint reach `fallback_cadence` — even inside a long
 * group. Otherwise a group boundary is the only schedule, and a 9-ticket group
 * delays feedback by 9 tickets. The structural gate keeps the boundary-only
 * schedule (its own reviewed set already bounds it).
 *
 * `reviewedGroups` is the CALLER's dedup set: each gate passes its own record
 * (goal_reviews for goal, structural_reviews for structural) so one gate
 * firing no longer suppresses the other (gh #107-C2). Candidate detection is
 * otherwise pure.
 */
export function detectGroupCheckpoints(
  state: RunState,
  ticket: TicketState,
  reviewedGroups: Iterable<string>,
  opts: { cadenceCeiling?: boolean } = {},
): string[] {
  const reviewed = new Set(reviewedGroups);
  const result: string[] = [];
  const fallback = state.config.goal_review?.fallback_cadence ?? 4;

  if (ticket.group) {
    const allInGroup = state.tickets.filter((t) => t.group === ticket.group);
    const allCommitted = allInGroup.length > 0 && allInGroup.every((t) => t.status === "committed");
    if (allCommitted && !reviewed.has(ticket.group)) {
      result.push(ticket.group);
      return result;
    }
    if (opts.cadenceCeiling !== true) return result;
  } else {
    const committedCount = state.tickets.filter((t) => t.status === "committed").length;
    if (opts.cadenceCeiling !== true) {
      // Legacy fallback: only for plans with no group labels at all.
      if (state.tickets.some((t) => t.group)) return result;
      if (committedCount > 0 && committedCount % fallback === 0) {
        const synthetic = `checkpoint-${committedCount}`;
        if (!reviewed.has(synthetic)) result.push(synthetic);
      }
      return result;
    }
  }

  // ADR 0044: the ceiling — commits since the last goal checkpoint, not a
  // modulo, so a skipped/failed review is retried at the next commit instead
  // of waiting for another full cadence.
  const committedCount = state.tickets.filter((t) => t.status === "committed").length;
  const sinceLast = committedCount - (state.last_goal_commit_count ?? 0);
  if (committedCount > 0 && sinceLast >= fallback) {
    const synthetic = `checkpoint-${committedCount}`;
    if (!reviewed.has(synthetic)) result.push(synthetic);
  }
  return result;
}

/** The goal gate's unreviewed reached checkpoints — `goal_reviews` is its
 * dedup set. Also the predicate run.ts's #62 browser-serialization guard uses
 * to decide whether the goal pass will fire. */
export function goalCheckpointsToFire(state: RunState, ticket: TicketState): string[] {
  return detectGroupCheckpoints(state, ticket, (state.goal_reviews ?? []).map((r) => r.group), { cadenceCeiling: true });
}

/**
 * Issue #19: Run a single goal-review checkpoint (or, with `runEnd`, the
 * issue #73 end-of-run goal review). Spawns a fresh opencode
 * process with the goal model, builds the prompt from the original goal +
 * design.md + architecture.md + cumulative contracts, parses the verdict, and
 * on FAIL generates corrective tickets that block all uncommitted tickets
 * (preserving group coherence), then processes them through the full pipeline.
 *
 * Mirrors the visual end-of-run loop semantics: pass returns, inconclusive
 * returns (no corrective tickets, honest status), fail with [BLOCKER]s
 * generates and processes corrective tickets inline. Returns "stop" when the
 * review converges on an identical finding set to the previous round of this
 * checkpoint — the caller must break its loop; the corrective pipeline would
 * only regenerate the same tickets as no-op commits. Returns "corrected" when
 * a corrective ticket actually committed inline (the one outcome that warrants
 * re-reviewing, gh #116) — distinct from "pass", which covers pass,
 * inconclusive, a blocker-less soft-pass, and a replan that superseded the
 * frontier.
 */
export async function runGoalReview(
  state: RunState,
  ledger: string,
  group: string,
  runTicket: RunTicket,
  opts?: { runEnd?: boolean },
): Promise<"pass" | "fail" | "stop" | "corrected"> {
  const cfg = state.config.goal_review!;
  const goalModel = state._models?.goal ?? null;
  if (!goalModel) return "pass";

  // ADR 0029 (#102): a mid-run group checkpoint under `checkpoint_action:
  // "advisory"` judges, records, and steers — it never corrects inline. The
  // run-end pass (opts.runEnd) is always the corrective seat, and a `medium`
  // gate ignores the knob, so mode decides there (see goalCheckpointIsAdvisory).
  const advisory = goalCheckpointIsAdvisory(cfg, opts?.runEnd);
  const seat = advisory ? "advisory checkpoint" : `checkpoint "${group}"`;

  const allTickets = await loadTickets(state.tickets_dir);

  // ADR 0044: a group with no rendered/interactive surface has nothing for a
  // browser-driving goal pass to judge — the cheap structural gate owns it.
  // Record the checkpoint as reviewed (so the scheduler dedupes it) and keep
  // the cadence baseline current.
  if (!opts?.runEnd) {
    const groupTickets = allTickets.filter((t) => t.group === group);
    if (groupTickets.length > 0 && !groupTickets.some((t) => touchesVisualSurface(t))) {
      recordGoalReview(state, { group, round: 0, verdict: "pass", findings: [] });
      state.last_goal_commit_count = state.tickets.filter((t) => t.status === "committed").length;
      await writeState(ledger, state);
      console.log(`[${nowClock()}] goal review — checkpoint "${group}": no rendered surface in this group — skipped (structural review covers it)`);
      return "pass";
    }
  }

  console.log(`\n[${nowClock()}] goal review — ${seat}`);

  const mission = allTickets[0]?.mission ?? "(no mission declared)";
  const runHint = runCommandFromVerify(state.config.verify, allTickets);

  const designDoc = await git.readProjectDoc(state.cwd, "docs/design.md");
  const architectureDoc = await git.readProjectDoc(state.cwd, "docs/architecture.md");
  const coherenceDoc = await git.readProjectDoc(state.cwd, "docs/coherence.md");
  const contractsIndex = await loadContracts(state.cwd);
  const contractsSummary = summarizeContracts(contractsIndex);

  const completedGroups = (state.goal_reviews ?? []).map((r) => r.group);
  const priorFindings = (state.goal_reviews ?? []).flatMap((r) => r.findings);

  const interactionHints = cfg.interaction_hints ?? null;
  // Issue #97: declared interface is authoritative; undeclared projects fall
  // back to canvas-only inference (today's behavior). The goal seat receives
  // the same interface rows as visual — the old `isGameCanvas` here was
  // computed then dropped, an asymmetry #97's row design removes.
  const projectInterface = state.config.projectInterface ?? ((await detectGameCanvas(state.cwd)) ? "canvas" : null);

  const groupDeliverables = allTickets
    .filter((t) => t.group === group)
    .map((t) => ({ title: t.title, what: t.what }));

  const committedFiles = new Set(
    state.tickets.filter((t) => t.status === "committed").map((t) => t.file),
  );
  const pendingDeliverables = allTickets
    .filter((t) => !committedFiles.has(t.file))
    .map((t) => ({ title: t.title, what: t.what }));

  // Issue #117: give the checkpoint reviewer the plan's remaining shape — the
  // groups still ahead (with their tickets) so "deferred to a later group" is
  // falsifiable, and an explicit final-group signal when nothing remains.
  // Only a real group checkpoint has a boundary to frame: run-end and synthetic
  // (checkpoint-N) checkpoints leave these undefined (no change to their scope).
  const pending = allTickets.filter((t) => !committedFiles.has(t.file));
  const remainingGroups = remainingPlanGroups(pending);
  const isFinalGroup = !opts?.runEnd && pending.length === 0 && groupDeliverables.length > 0;

  // ADR 0043: only demand a full core-loop playthrough once the build can
  // actually complete the loop — before the terminal-state owner commits, the
  // required playthrough is scoped to this group's deliverables. The signal is
  // deliberately conservative: a ticket whose title/body names the run
  // lifecycle (or the terminal boss/finale) counts as an owner, and while any
  // such ticket is pending the loop is treated as not ready. A false "not
  // ready" only scopes the playthrough (safe); a false "ready" would recreate
  // the out-of-scope blocker this rule exists to prevent.
  const lifecycleOwnerRe = /\b(state machine|run lifecycle|game state|gameplay loop|win condition|victory|death|boss|finale)\b/i;
  const ownsLifecycle = (t: { title: string; what: string }): boolean => lifecycleOwnerRe.test(`${t.title} ${t.what}`);
  const pendingOwnsLifecycle = pending.some(ownsLifecycle);
  const committedOwnsLifecycle = allTickets.some((t) => committedFiles.has(t.file) && ownsLifecycle(t));
  const coreLoopReady = opts?.runEnd === true || isFinalGroup || (committedOwnsLifecycle && !pendingOwnsLifecycle);
  const pendingFiles = new Set(pending.flatMap((t) => t.files));

  // ADR 0040: criteria the builder recorded as unverified ride into every
  // goal checkpoint as explicit must-check items.
  const unverifiedCriteria = state.tickets
    .filter((t) => t.status === "committed" && (t.unverified?.length ?? 0) > 0)
    .flatMap((t) => (t.unverified ?? []).map((u) => `${t.number} ${t.title}: ${u}`));

  const prompt = buildGoalReviewPrompt({
    originalPrompt: state.original_prompt ?? mission,
    designDoc,
    coherenceDoc,
    architectureDoc,
    contractsSummary,
    verifyCommands: state.config.verify,
    runCommandHint: runHint,
    group,
    completedGroups,
    priorFindings,
    learnings: await readLearnings(state.cwd),
    digest: await readDigest(state.cwd),
    interactionHints,
    projectInterface,
    groupDeliverables: groupDeliverables.length > 0 ? groupDeliverables : undefined,
    pendingDeliverables: pendingDeliverables.length > 0 ? pendingDeliverables : undefined,
    remainingGroups: remainingGroups.length > 0 ? remainingGroups : undefined,
    isFinalGroup: isFinalGroup || undefined,
    unverifiedCriteria: unverifiedCriteria.length > 0 ? unverifiedCriteria : undefined,
    coreLoopReady,
    advisory,
    visionCapability: await readVisionCapabilityFor(state.cwd, state._models?.goal ?? null),
  });

  // Every round gets its own ledger phase file. `goal-run-end` without a round
  // suffix once collected ALL rounds' transcripts (the events files are
  // append-only), and parseGoalVerdict takes the FIRST $GOAL_FAIL block — so
  // round 1+ parsed round 0's stale verdict and regenerated its corrective
  // tickets verbatim, even when the reviewer had actually passed
  // (run-20260907-1340: round 1's real verdict was $GOAL_PASS; the railhead
  // looped twice more churning no-op corrective commits).
  const groupRecords = (state.goal_reviews ?? []).filter((r) => r.group === group);
  const previous = groupRecords[groupRecords.length - 1];
  const round = groupRecords.length;
  const basePhaseFile = `goal-${group.replace(/[^a-z0-9-]/gi, "-")}`;
  const phaseFile = round === 0 ? basePhaseFile : `${basePhaseFile}-r${round}`;
  // Issue #89: the opencode invocation + transcript extraction + exit
  // classification for every review kind lives in one runner (runReviewAgent);
  // per-kind policy (record, corrective/replan handling) stays here.
  const agentOutcome = await runReviewAgent({
    label: "goal review",
    prompt,
    cwd: state.cwd,
    ledgerDir: ledger,
    phaseFile,
    model: goalModel,
    agent: RAILHEAD_AGENT_NAMES.observe,
    live: !state.quiet,
    verbose: state.verbose,
    heartbeat: true,
    livePrefix: "goal",
    maxSteps: state.config.max_phase_steps,
    stallTimeoutSec: state.config.stall_timeout_sec,
    maxStepModelSec: state.config.max_step_model_sec,
    maxContextTokens: contextBudget(state),
  });
  if (agentOutcome.status === "fatal") {
    // The goal model's quota is exhausted (a 403 usage-limit wall, not a
    // retryable rate limit) — no retry within the run's window will help. This
    // is the seat that judges whether the build meets the goal, so a silent
    // inconclusive here would let an unverified build ship. Surface it as a
    // hard failure: record why, mark the run, and stop the gate.
    const message = `goal review unavailable — ${agentOutcome.detail}`;
    console.log(`[${nowClock()}] ${message}; marking the run ${state.pause_on_failure ? "stopped" : "failed"}`);
    recordGoalReview(state, { group, round, verdict: "inconclusive", findings: [message] });
    state.status = state.pause_on_failure ? "stopped" : "failed";
    await writeState(ledger, state);
    return "fail";
  }
  if (agentOutcome.status !== "ok") {
    console.log(`[${nowClock()}] goal review: agent ${agentOutcome.detail}; inconclusive — agent produced no verdict`);
    recordGoalReview(state, { group, round, verdict: "inconclusive", findings: [] });
    await writeState(ledger, state);
    return "pass";
  }

  const transcript = agentOutcome.transcript;
  await pushLearnings(state, ledger, phaseFile);
  // ADR 0018: the goal reviewer's architectural-state DIGEST: lines ride out
  // too (structural-loop already pushes its own seat's); a goal checkpoint is
  // exactly when a module shape milestone lands.
  await pushDigest(state.cwd, transcript, group);

  // Issue #99 (ADR 0028): the goal reviewer is the charter's judge. Any
  // `CHARTER:` revisions it emitted are applied to docs/coherence.md BEFORE
  // corrective tickets are generated (sequencing) so correctives are authored
  // against the amended contract; the update-wins precedence over conflicting
  // findings is realized because the corrective implementer holds the amended
  // charter as authoritative.
  const charterRevisions = parseCharterRevisions(transcript);
  if (charterRevisions.length > 0) {
    const applied = await applyCharterRevisions(state.cwd, charterRevisions);
    if (applied) {
      console.log(`[${nowClock()}] goal review: applied ${charterRevisions.length} CHARTER: revision(s) to docs/coherence.md before corrective generation`);
    }
  }

  let verdict = parseGoalVerdict(transcript);
  // Issue #97: the goal gate absorbs the ADR 0009 downgrade, keyed to the
  // declared interface. A PASS whose phase ledger shows no real user-level
  // operation (a browser-ui reviewer that drove everything through synthetic
  // `evaluate_script` dispatch) downgrades to INCONCLUSIVE — no corrective
  // tickets, honest record, run proceeds. `none`/`canvas`/undeclared never
  // require it (the declaration is the exemption).
  if (verdict.verdict === "pass" && requiresRealInputEvidence(projectInterface)) {
    const downgrade = await checkGoalInteractionEvidence(ledger, phaseFile, projectInterface);
    if (downgrade) {
      verdict = { verdict: "inconclusive", findings: [`[evidence downgrade] $GOAL_PASS reclassified as INCONCLUSIVE — ${downgrade}`] };
    }
  }
  recordGoalReview(state, { group, round, verdict: verdict.verdict, findings: verdict.findings, advisory: advisory || undefined });
  // ADR 0044: the cadence ceiling measures from the last goal checkpoint,
  // whatever its verdict — pass, fail, advisory, or inconclusive.
  state.last_goal_commit_count = state.tickets.filter((t) => t.status === "committed").length;
  await writeState(ledger, state);

  if (verdict.verdict === "pass") {
    console.log(`[${nowClock()}] goal review ✓ PASS (${seat})`);
    return "pass";
  }
  if (verdict.verdict === "inconclusive") {
    console.log(`[${nowClock()}] goal review ⚠ INCONCLUSIVE (${seat}) — agent produced no verdict; no corrective tickets generated`);
    return "pass";
  }

  // ADR 0029 (#102): advisory checkpoints see-early/steer-early/correct-once.
  // The judge's findings are already recorded (the run-end pass flatMaps them
  // as prior findings) and the charter/digest/learnings markers already pushed
  // above — that IS the steering into later groups. Zero corrective tickets
  // are generated, no replan fires, no re-review loop runs; the single
  // corrective batch happens at run end. The convergence stop never applies:
  // advisory is one round by construction.
  if (advisory) {
    console.log(`[${nowClock()}] goal review ○ ADVISORY ${reviewSummary(verdict.findings)} — recorded + steering; zero corrective tickets (corrected in one batch at run end)`);
    return "pass";
  }

  // Convergence stop: the identical finding set twice in a row means the
  // corrective cycle produced no observable change — regenerating the same
  // corrective tickets would be no-op-churn (belt: also fires if a model ever
  // echoes its injected prior-findings block verbatim).
  if (previous?.verdict === "fail" && findingsEchoLastRound(previous.findings, verdict.findings)) {
    console.log(`[${nowClock()}] goal review ⚠ checkpoint "${group}": identical findings as the previous round after a corrective cycle — corrections are not landing; stopping the review loop (resume with a replan or a manual fix)`);
    return "stop";
  }

  // ADR 0043: enforce the blocker evidence rule before any corrective work.
  // A blocker that cites no artifact present in the current tree, or only
  // files owned by unbuilt tickets, is out of scope at this checkpoint — it
  // stays in the review record (steering) but generates no ticket.
  const anchored = splitAnchoredBlockers(verdict.findings, {
    exists: (rel) => existsSync(join(state.cwd, rel)),
    pendingFiles,
  });
  for (const u of anchored.unanchored) {
    console.log(`[${nowClock()}] goal review: [BLOCKER] typed steering-only — ${u.reason}`);
  }

  // Issue #67: prefer the reviewer's $CORRECTIVE decomposition when present;
  // fall back to the mechanical one-ticket-per-finding split otherwise. The
  // $REPLAN check (the beforeCorrectives hook) supersedes both when it runs.
  const suggested = parseCorrectiveTickets(transcript);

  let replanTriggered = false;
  let replanFailed = false;
  const maxReplans = cfg.max_replans ?? DEFAULT_MAX_REPLANS;
  const outcome = await processCorrectiveFindings(state, ledger, anchored.findings, {
    kind: "goal",
    label: `goal review (checkpoint "${group}")`,
    mission,
    blockUncommitted: true,
    suggested: suggested ?? undefined,
    runTicket,
    beforeCorrectives: async () => {
      // gh #116: cap replans per run. Once the plan has been re-scoped
      // `maxReplans` times, a further $REPLAN is refused — the verdict falls
      // back to corrective tickets (or soft-passes) rather than churning the
      // planner on a loop that cannot produce a different plan.
      const replans = state.replan_count ?? 0;
      if (replans >= maxReplans) {
        console.log(`[${nowClock()}] goal review: plan re-scoped ${replans} time(s); stopping — max_replans (${maxReplans}) reached`);
        return false;
      }
      replanTriggered = await replanFromCheckpoint(state, ledger, verdict.findings, group, transcript);
      if (replanTriggered) {
        state.replan_count = replans + 1;
        console.log(`[${nowClock()}] goal review: replan ${state.replan_count}/${maxReplans} triggered for checkpoint "${group}"`);
        // A run-end replan regenerates a frontier with no build loop left to
        // process it — drain it inline (dependency order) so the new tickets
        // actually build. A failed drain flips status; surface as a gate failure.
        if (opts?.runEnd) {
          const drained = await drainFrontier(state, ledger, runTicket);
          if (!drained) {
            if (!isFinished(state.status)) {
              state.status = state.pause_on_failure ? "stopped" : "failed";
            }
            await writeState(ledger, state);
            replanFailed = true;
          }
        }
      }
      return replanTriggered;
    },
  });
  if (replanTriggered) {
    if (replanFailed) {
      console.log(`[${nowClock()}] goal review: replanned ticket failed at run-end; stopping goal review`);
      return "fail";
    }
    console.log(`[${nowClock()}] goal review: replan triggered for checkpoint "${group}"; corrective tickets superseded by regenerated frontier`);
    return "pass";
  }
  if (outcome === "none") {
    console.log(`[${nowClock()}] goal review ⚠ FAIL with no [BLOCKER] — soft-pass; ${reviewSummary(verdict.findings)} noted`);
    return "pass";
  }
  if (outcome === "halted") {
    console.log(`[${nowClock()}] goal review: halted by an agent-initiated stop signal; stopping goal review`);
    return "fail";
  }
  if (outcome === "failed") {
    console.log(`[${nowClock()}] goal review: corrective ticket failed; stopping goal review`);
    return "fail";
  }
  console.log(`[${nowClock()}] goal review: corrective ticket(s) committed for checkpoint "${group}"`);
  return "corrected";
}

function recordGoalReview(
  state: RunState,
  record: GoalReviewRecord,
): void {
  if (!state.goal_reviews) state.goal_reviews = [];
  state.goal_reviews.push(record);
}

/** Issue #97: check a goal PASS's phase ledger for real user-level operation
 * appropriate to the project's declared interface. Returns the reason a PASS
 * must downgrade, or null when the evidence holds (or the interface requires
 * none). Mirrors the visual whole-app check's semantics row-for-row. */
async function checkGoalInteractionEvidence(
  ledger: string,
  phaseFile: string,
  projectInterface: ProjectInterface | null,
): Promise<string | null> {
  let raw: string;
  try {
    raw = await readFile(eventPath(ledger, phaseFile), "utf8");
  } catch {
    return null;
  }
  const calls = parseToolCalls(raw);
  const { ok, missing } = hasInteractionEvidence(calls, projectInterface);
  if (ok) return null;
  console.log(
    `[${nowClock()}] goal review: $GOAL_PASS downgraded to INCONCLUSIVE — ${missing}`,
  );
  return missing;
}

/**
 * Issue #73: end-of-run goal review. When goal_review.mode is `full` or
 * `light`, once the run's tickets commit, a final holistic goal review runs —
 * after the end-of-run visual pass, whose screenshots are evidence the goal
 * reviewer can reference. Mirrors the visual end-of-run loop: bounded by
 * `max_rounds`, FAIL with [BLOCKER]s generates corrective tickets processed
 * inline. Skips silently when tickets remain pending (resume runs it once they
 * commit) or when nothing has committed to evaluate.
 */
export async function goalReviewAtRunEnd(
  state: RunState,
  ledger: string,
  runTicket: RunTicket,
): Promise<"pass" | "fail"> {
  const cfg = state.config.goal_review;
  if (!cfg || !firesAtRunEnd(cfg.mode)) return "pass";
  const goalModel = state._models?.goal ?? null;
  if (goalModel === null) return "pass";
  const committed = state.tickets.filter((t) => t.status === "committed");
  if (committed.length === 0) {
    console.log("\ngoal review (run-end): skipped (no committed tickets to review)");
    return "pass";
  }
  const pending = state.tickets.filter((t) => t.status !== "committed" && t.status !== "skipped");
  if (pending.length > 0) {
    console.log(`\ngoal review (run-end): skipped (${pending.length} ticket(s) still pending — resume will run it after they complete)`);
    return "pass";
  }

  const group = "run-end";
  const maxRounds = cfg.max_rounds ?? state.config.max_attempts ?? (state.config.max_retries * 3);
  for (let attempt = 0; attempt < maxRounds; attempt++) {
    const outcome = await runGoalReview(state, ledger, group, runTicket, { runEnd: true });
    if (outcome === "fail") return "fail";
    // Convergence stop: the round produced the same finding set as the one the
    // corrective cycle just addressed — another round would only re-review
    // unchanged work, so the loop ends here even though the record is "fail".
    if (outcome === "stop") return "pass";
    // gh #116: only a round that actually committed corrective tickets — a
    // corrective cycle that may have left the goal still unmet — warrants
    // another full review pass, bounded by maxRounds. A pass, an
    // inconclusive, a blocker-less soft-pass, or a replan all end the loop:
    // re-running any of those could not change the outcome.
    if (outcome !== "corrected") return "pass";
  }
  console.log(`[${nowClock()}] goal review (run-end): max rounds (${maxRounds}) reached; stopping`);
  return "pass";
}
